"""
Weather Service — Open-Meteo live API + optional trained weather-fit scorer.

Live API: Open-Meteo (https://open-meteo.com) — no API key required.
Endpoint: GET https://api.open-meteo.com/v1/forecast
  ?latitude=X&longitude=Y
  &daily=temperature_2m_max,precipitation_probability_max
  &forecast_days=7

Caching: in-memory dict keyed by (lat_rounded, lng_rounded) with 1-hour TTL.
  Using a simple dict + timestamp instead of functools.lru_cache because
  lru_cache doesn't support TTL expiry natively.

Bonus — Weather-fit score model:
  Labels generated by rule:
    rainfall_penalty = min(100, avgRainfallMm / 10)       for outdoor activities
                     = min(40,  avgRainfallMm / 25)       for indoor activities
    temp_penalty     = max(0, |avgTempC - 25| - 3) * 2    (ideal 22–28°C band)
    humidity_penalty = max(0, (avgHumidityPct - 70) / 3)  (above 70% is uncomfortable)
    weather_fit_score = max(0, 100 - rainfall_penalty - temp_penalty - humidity_penalty)

  Features: [avgTempC, avgRainfallMm, avgHumidityPct, monsoonSeason_int, activityType_int]
  Model: GradientBoostingRegressor (sklearn)

should_reoptimize():
  Returns True when precipitation_probability_max > PRECIP_THRESHOLD (default 60%)
  during an outdoor activity on the queried date.
"""

import json, logging, time
from datetime import date, datetime
from typing import Optional
import httpx
import numpy as np
import joblib
import os
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

logger = logging.getLogger(__name__)

OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"
CACHE_TTL_SECS = 3600  # 1 hour
PRECIP_THRESHOLD = 60.0  # % precipitation probability → trigger reoptimise

MONTHS_ORDER = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December",
]

WEATHER_FIT_MODEL_FILE = "weather_fit_model.pkl"


# ── In-memory TTL cache ────────────────────────────────────────────────────────
_cache: dict[tuple, dict] = {}

def _cache_key(lat: float, lng: float) -> tuple:
    return (round(lat, 2), round(lng, 2))

def _cache_get(key: tuple) -> Optional[dict]:
    entry = _cache.get(key)
    if entry and (time.time() - entry["ts"]) < CACHE_TTL_SECS:
        return entry["data"]
    return None

def _cache_set(key: tuple, data: dict):
    _cache[key] = {"data": data, "ts": time.time()}


# ── Open-Meteo fetch ──────────────────────────────────────────────────────────
async def fetch_forecast(lat: float, lng: float) -> dict:
    key = _cache_key(lat, lng)
    cached = _cache_get(key)
    if cached:
        logger.debug("Weather cache hit for (%.2f, %.2f)", lat, lng)
        return cached

    params = {
        "latitude": lat,
        "longitude": lng,
        "daily": "temperature_2m_max,precipitation_probability_max",
        "forecast_days": 7,
        "timezone": "Asia/Kolkata",
    }
    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.get(OPEN_METEO_URL, params=params)
        resp.raise_for_status()
        raw = resp.json()

    daily = raw.get("daily", {})
    dates        = daily.get("time", [])
    temps_max    = daily.get("temperature_2m_max", [])
    precip_probs = daily.get("precipitation_probability_max", [])

    forecast = [
        {
            "date": dates[i],
            "tempMaxC": temps_max[i],
            "precipitationProbabilityPct": precip_probs[i],
        }
        for i in range(len(dates))
    ]
    result = {
        "lat": lat,
        "lng": lng,
        "forecast": forecast,
        "source": "open-meteo.com",
        "cachedAt": datetime.utcnow().isoformat() + "Z",
    }
    _cache_set(key, result)
    return result


# ── should_reoptimize helper ──────────────────────────────────────────────────
async def should_reoptimize(
    lat: float,
    lng: float,
    query_date: date,
    activity_indoor_outdoor: str,
    threshold: float = PRECIP_THRESHOLD,
) -> dict:
    """
    Returns True when an outdoor activity on `query_date` faces >threshold%
    precipitation probability. Indoor activities are never flagged for replanning.
    """
    if activity_indoor_outdoor == "indoor":
        return {
            "shouldReoptimize": False,
            "reason": "Indoor activity — weather does not affect the plan",
            "precipitationPct": None,
        }
    try:
        forecast_data = await fetch_forecast(lat, lng)
        target = query_date.isoformat()
        day_entry = next(
            (d for d in forecast_data["forecast"] if d["date"] == target), None
        )
        if not day_entry:
            return {
                "shouldReoptimize": False,
                "reason": "No forecast data for the requested date",
                "precipitationPct": None,
            }
        precip = day_entry.get("precipitationProbabilityPct", 0) or 0
        trigger = precip > threshold
        return {
            "shouldReoptimize": trigger,
            "precipitationPct": precip,
            "threshold": threshold,
            "reason": (
                f"Precipitation probability {precip}% exceeds threshold {threshold}% — recommend indoor alternatives"
                if trigger
                else f"Precipitation probability {precip}% is below threshold — outdoor activity safe"
            ),
        }
    except Exception as e:
        logger.warning("should_reoptimize failed: %s", e)
        return {
            "shouldReoptimize": False,
            "reason": f"Weather API unavailable: {e}",
            "precipitationPct": None,
        }


# ── Bonus: Weather-fit score model ────────────────────────────────────────────
def _weather_fit_label(row: dict, activity_type: str) -> float:
    """
    Rule-based label generator.
    rainfall_penalty scales differently for indoor vs outdoor.
    """
    rain = row.get("avgRainfallMm", 0)
    temp = row.get("avgTempC", 25)
    hum  = row.get("avgHumidityPct", 60)

    if activity_type == "outdoor":
        rain_penalty = min(100.0, rain / 10.0)
    else:
        rain_penalty = min(40.0, rain / 25.0)

    temp_penalty = max(0.0, (abs(temp - 25.0) - 3.0) * 2.0)  # ideal 22–28°C
    hum_penalty  = max(0.0, (hum - 70.0) / 3.0)

    score = max(0.0, 100.0 - rain_penalty - temp_penalty - hum_penalty)
    return round(score, 2)


class WeatherFitService:
    def __init__(self, data_path: str, model_dir: str):
        with open(data_path, encoding="utf-8") as f:
            raw: list[dict] = json.load(f)
        self._climate = raw
        self._by_dest_month: dict[tuple[str, str], dict] = {
            (r["destinationId"], r["month"]): r for r in raw
        }
        self._model_dir = model_dir
        self._model: Optional[GradientBoostingRegressor] = None
        self._load_or_train()

    def _model_path(self) -> str:
        return os.path.join(self._model_dir, WEATHER_FIT_MODEL_FILE)

    def _load_or_train(self):
        if os.path.exists(self._model_path()):
            try:
                self._model = joblib.load(self._model_path())
                logger.info("Weather-fit model loaded from %s", self._model_path())
                return
            except Exception as e:
                logger.warning("Could not load weather-fit model (%s) — retraining", e)
        self._train()

    def _train(self):
        X_rows, y_rows = [], []
        for row in self._climate:
            for activity_type_int, activity_type_str in [(0, "indoor"), (1, "outdoor")]:
                label = _weather_fit_label(row, activity_type_str)
                X_rows.append([
                    row.get("avgTempC", 25),
                    row.get("avgRainfallMm", 0),
                    row.get("avgHumidityPct", 60),
                    1 if row.get("monsoonSeason") else 0,
                    activity_type_int,
                ])
                y_rows.append(label)

        X = np.array(X_rows)
        y = np.array(y_rows)

        # ── Evaluation: 80/20 split to report MAE ──────────────────────────
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )
        eval_model = GradientBoostingRegressor(
            n_estimators=100, max_depth=4, random_state=42
        )
        eval_model.fit(X_train, y_train)
        y_pred = eval_model.predict(X_test)
        mae = mean_absolute_error(y_test, y_pred)
        logger.info(
            "Weather-fit model evaluation — MAE on 20%% test set (%d samples): %.2f",
            len(X_test), mae,
        )

        # ── Final model: fit on ALL data for production ────────────────────
        self._model = GradientBoostingRegressor(
            n_estimators=100, max_depth=4, random_state=42
        )
        self._model.fit(X, y)
        os.makedirs(self._model_dir, exist_ok=True)
        joblib.dump(self._model, self._model_path())
        logger.info("Weather-fit model trained on %d samples", len(X_rows))

    def retrain(self) -> dict:
        """Force retrain the model and save to disk. Returns training summary."""
        self._train()
        return {
            "model": "WeatherFitService (GradientBoostingRegressor)",
            "saved_to": self._model_path(),
            "n_climate_entries": len(self._climate),
        }

    def get_fit_score(self, destination_id: str, month: str, activity_type: str) -> dict:
        key = (destination_id, month)
        row = self._by_dest_month.get(key)
        if not row:
            return {
                "destinationId": destination_id,
                "month": month,
                "activityType": activity_type,
                "warning": "No climate data for this destination/month combination",
            }
        if self._model is None:
            raise RuntimeError("Weather-fit model not initialised")

        activity_int = 1 if activity_type == "outdoor" else 0
        features = np.array([[
            row.get("avgTempC", 25),
            row.get("avgRainfallMm", 0),
            row.get("avgHumidityPct", 60),
            1 if row.get("monsoonSeason") else 0,
            activity_int,
        ]])
        score = float(self._model.predict(features)[0])
        score = max(0.0, min(100.0, score))

        return {
            "destinationId": destination_id,
            "month": month,
            "activityType": activity_type,
            "weatherFitScore": round(score, 1),
            "interpretation": (
                "Excellent" if score >= 80
                else "Good" if score >= 60
                else "Fair" if score >= 40
                else "Poor"
            ),
            "climateData": {
                "avgTempC": row.get("avgTempC"),
                "avgRainfallMm": row.get("avgRainfallMm"),
                "avgHumidityPct": row.get("avgHumidityPct"),
                "monsoonSeason": row.get("monsoonSeason"),
            },
        }
